In [1]:
import zipfile
import os

zip_files = ['archive (7).zip', 'archive (8).zip', 'archive (9).zip']

for zip_file in zip_files:
    print(f"Extracting {zip_file}...")
    with zipfile.ZipFile(zip_file, 'r') as z:
        z.extractall('.')
    print(f"Done!")

print("\nAll files extracted!")
print(os.listdir('.'))

Extracting archive (7).zip...
Done!
Extracting archive (8).zip...
Done!
Extracting archive (9).zip...
Done!

All files extracted!
['.ipynb_checkpoints', '.virtual_documents', '2014_Financial_Data.csv', '2015_Financial_Data.csv', '2016_Financial_Data.csv', '2017_Financial_Data.csv', '2018_Financial_Data.csv', 'anaconda_projects', 'archive (7).zip', 'archive (8).zip', 'archive (9).zip', 'etfs', 'fundamentals.csv', 'prices-split-adjusted.csv', 'prices.csv', 'securities.csv', 'stocks', 'symbols_valid_meta.csv', 'Untitled.ipynb']

In [63]:
import pandas as pd


# List all yearly files
files = [
    "2014_Financial_Data.csv",
    "2015_Financial_Data.csv",
    "2016_Financial_Data.csv",
    "2017_Financial_Data.csv",
    "2018_Financial_Data.csv"
]

# Store all dataframes
df_list = []

In [64]:

for file in files:
    df = pd.read_csv(file)
    year = file.split("_")[0]
    df['year'] = int(year)
    
    df_list.append(df)

financials = pd.concat(df_list, ignore_index=True)

print(financials.shape)

(22077, 230)

In [65]:
financials.head(10)

,Unnamed: 0,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,Interest Expense,...,R&D Expense Growth,SG&A Expenses Growth,Sector,2015 PRICE VAR [%],Class,year,2016 PRICE VAR [%],2017 PRICE VAR [%],2018 PRICE VAR [%],2019 PRICE VAR [%]
0,PG,7.440100e+10,-0.0713,3.903000e+10,3.537100e+10,0.000000e+00,2.146100e+10,2.146100e+10,1.391000e+10,7.090000e+08,...,0.0000,-0.1746,Consumer Defensive,-9.323276,0,2014,NaN,NaN,NaN,NaN
1,VIPS,3.734148e+09,1.1737,2.805625e+09,9.285226e+08,1.083303e+08,3.441414e+08,7.939267e+08,1.345959e+08,1.214869e+07,...,1.6484,1.7313,Consumer Defensive,-25.512193,0,2014,NaN,NaN,NaN,NaN
2,KR,9.837500e+10,0.0182,7.813800e+10,2.023700e+10,0.000000e+00,1.519600e+10,1.751200e+10,2.725000e+09,4.430000e+08,...,0.0000,0.0234,Consumer Defensive,33.118297,1,2014,NaN,NaN,NaN,NaN
3,RAD,2.552641e+10,0.0053,1.820268e+10,7.323734e+09,0.000000e+00,6.561162e+09,6.586482e+09,7.372520e+08,4.245910e+08,...,0.0000,-0.0060,Consumer Defensive,2.752291,1,2014,NaN,NaN,NaN,NaN
4,GIS,1.790960e+10,0.0076,1.153980e+10,6.369800e+09,0.000000e+00,3.474300e+09,3.412400e+09,2.957400e+09,3.024000e+08,...,0.0000,-0.0220,Consumer Defensive,12.897715,1,2014,NaN,NaN,NaN,NaN
5,PM,8.010600e+10,0.0010,6.077500e+10,1.933100e+10,0.000000e+00,7.001000e+09,7.629000e+09,1.170200e+10,1.052000e+09,...,0.0000,0.0161,Consumer Defensive,13.980937,1,2014,NaN,NaN,NaN,NaN
6,KO,4.599800e+10,-0.0183,1.788900e+10,2.810900e+10,0.000000e+00,1.721800e+10,1.840100e+10,9.708000e+09,4.830000e+08,...,0.0000,-0.0053,Consumer Defensive,5.339413,1,2014,NaN,NaN,NaN,NaN
7,WMT,4.762940e+11,0.0163,3.580690e+11,1.182250e+11,0.000000e+00,9.135300e+10,9.135300e+10,2.687200e+10,2.335000e+09,...,0.0000,0.0307,Consumer Defensive,-26.653702,0,2014,NaN,NaN,NaN,NaN
8,MDLZ,3.424400e+10,-0.0299,2.164700e+10,1.259700e+10,0.000000e+00,8.457000e+09,9.355000e+09,3.242000e+09,6.880000e+08,...,0.0000,-0.0256,Consumer Defensive,23.809818,1,2014,NaN,NaN,NaN,NaN
9,MO,2.452200e+10,0.0023,1.436200e+10,1.016000e+10,0.000000e+00,2.539000e+09,2.540000e+09,7.620000e+09,8.080000e+08,...,0.0000,0.0850,Consumer Defensive,23.865489,1,2014,NaN,NaN,NaN,NaN

In [66]:
financials.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22077 entries, 0 to 22076
Columns: 230 entries, Unnamed: 0 to 2019 PRICE VAR [%]
dtypes: float64(226), int64(2), object(2)
memory usage: 38.7+ MB

In [67]:
financials.describe()

,Revenue,Revenue Growth,Cost of Revenue,Gross Profit,R&D Expenses,SG&A Expense,Operating Expenses,Operating Income,Interest Expense,Earnings before Tax,...,Debt Growth,R&D Expense Growth,SG&A Expenses Growth,2015 PRICE VAR [%],Class,year,2016 PRICE VAR [%],2017 PRICE VAR [%],2018 PRICE VAR [%],2019 PRICE VAR [%]
count,2.090600e+04,19989.000000,2.030600e+04,2.087000e+04,1.993900e+04,2.040800e+04,2.037500e+04,2.097600e+04,2.035800e+04,2.071300e+04,...,19462.000000,19598.000000,19655.000000,3.808000e+03,22077.000000,22077.000000,4120.000000,4.797000e+03,4960.000000,4392.000000
mean,5.161619e+09,3.622214,3.258565e+09,1.970452e+09,1.033333e+08,8.699279e+08,1.368670e+09,5.896979e+08,9.778939e+07,4.925003e+08,...,3.733922,0.295610,0.365149,9.751560e+02,0.550754,2016.090954,103.077642,3.650260e+02,-4.461547,20.803948
std,3.197314e+10,312.648170,2.583092e+10,8.735750e+09,7.676062e+08,3.804283e+09,5.662984e+09,2.976454e+09,4.996543e+08,2.484345e+09,...,174.864701,12.974127,15.030054,4.098461e+04,0.497429,1.374340,3756.530836,1.940149e+04,561.802215,82.622147
min,-6.276160e+08,-12.769300,-2.986888e+09,-1.280800e+10,-1.098000e+08,-1.401594e+08,-5.495512e+09,-1.933900e+10,-1.710954e+09,-2.177200e+10,...,-1.051000,-2.662200,-2.369900,-1.003972e+02,0.000000,2014.000000,-99.947830,-9.999941e+01,-99.999115,-99.864779
25%,5.880737e+07,-0.014700,3.211750e+06,3.035575e+07,0.000000e+00,1.768550e+07,3.564150e+07,-4.433750e+06,0.000000e+00,-8.745000e+06,...,-0.067475,0.000000,-0.013700,-2.857143e+01,0.000000,2015.000000,-5.172844,-6.730768e+00,-33.388915,-7.477173
50%,4.352510e+08,0.057600,1.530115e+08,1.943525e+08,0.000000e+00,8.062450e+07,1.564000e+08,3.585350e+07,3.697000e+06,2.380000e+07,...,0.000000,0.000000,0.061000,-5.281842e+00,1.000000,2016.000000,17.278935,1.090686e+01,-13.336397,17.639393
75%,2.287259e+09,0.182400,1.180224e+09,8.806035e+08,1.220150e+07,3.699722e+08,6.210870e+08,2.554363e+08,4.969325e+07,1.964680e+08,...,0.150075,0.000000,0.185350,1.331484e+01,1.000000,2017.000000,40.567983,3.155634e+01,2.124593,39.625879
max,1.886894e+12,42138.663900,1.581527e+12,4.621600e+11,2.883700e+10,1.856830e+11,3.056050e+11,1.565540e+11,3.152300e+10,8.720500e+10,...,17646.823500,1542.611000,2042.000000,2.418601e+06,1.000000,2018.000000,212700.011623,1.321281e+06,39219.999109,3756.716345

In [68]:
financials.columns

Index(['Unnamed: 0', 'Revenue', 'Revenue Growth', 'Cost of Revenue',
       'Gross Profit', 'R&D Expenses', 'SG&A Expense', 'Operating Expenses',
       'Operating Income', 'Interest Expense',
       ...
       'R&D Expense Growth', 'SG&A Expenses Growth', 'Sector',
       '2015 PRICE VAR [%]', 'Class', 'year', '2016 PRICE VAR [%]',
       '2017 PRICE VAR [%]', '2018 PRICE VAR [%]', '2019 PRICE VAR [%]'],
      dtype='object', length=230)

In [69]:
financials.columns = (
    financials.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
    .str.replace("%", "pct")
    .str.replace("&", "_")
    .str.replace("[", "_")
    .str.replace("]", "_")
)

In [70]:
financials.rename(columns={'unnamed:_0': 'symbol'}, inplace=True)

In [71]:
financials.head()

,symbol,revenue,revenue_growth,cost_of_revenue,gross_profit,r_d_expenses,sg_a_expense,operating_expenses,operating_income,interest_expense,...,r_d_expense_growth,sg_a_expenses_growth,sector,2015_price_var__pct_,class,year,2016_price_var__pct_,2017_price_var__pct_,2018_price_var__pct_,2019_price_var__pct_
0,PG,7.440100e+10,-0.0713,3.903000e+10,3.537100e+10,0.000000e+00,2.146100e+10,2.146100e+10,1.391000e+10,7.090000e+08,...,0.0000,-0.1746,Consumer Defensive,-9.323276,0,2014,NaN,NaN,NaN,NaN
1,VIPS,3.734148e+09,1.1737,2.805625e+09,9.285226e+08,1.083303e+08,3.441414e+08,7.939267e+08,1.345959e+08,1.214869e+07,...,1.6484,1.7313,Consumer Defensive,-25.512193,0,2014,NaN,NaN,NaN,NaN
2,KR,9.837500e+10,0.0182,7.813800e+10,2.023700e+10,0.000000e+00,1.519600e+10,1.751200e+10,2.725000e+09,4.430000e+08,...,0.0000,0.0234,Consumer Defensive,33.118297,1,2014,NaN,NaN,NaN,NaN
3,RAD,2.552641e+10,0.0053,1.820268e+10,7.323734e+09,0.000000e+00,6.561162e+09,6.586482e+09,7.372520e+08,4.245910e+08,...,0.0000,-0.0060,Consumer Defensive,2.752291,1,2014,NaN,NaN,NaN,NaN
4,GIS,1.790960e+10,0.0076,1.153980e+10,6.369800e+09,0.000000e+00,3.474300e+09,3.412400e+09,2.957400e+09,3.024000e+08,...,0.0000,-0.0220,Consumer Defensive,12.897715,1,2014,NaN,NaN,NaN,NaN

In [72]:
price_cols = [col for col in financials.columns if "price_var" in col]

financials.drop(columns=price_cols, inplace=True)

In [73]:
growth_cols = [col for col in financials.columns if "growth" in col and col != "revenue_growth"]

financials.drop(columns=growth_cols, inplace=True)

In [74]:
financials.drop(columns=["class"], inplace=True)

In [75]:
keep_cols = [
    "symbol",
    "year",
    "revenue",
    "revenue_growth",
    "sector",
    "gross_profit",
    "operating_income",
    "operating_expenses",
    "cost_of_revenue"
]

financials = financials[keep_cols]

In [76]:
financials.head()

,symbol,year,revenue,revenue_growth,sector,gross_profit,operating_income,operating_expenses,cost_of_revenue
0,PG,2014,7.440100e+10,-0.0713,Consumer Defensive,3.537100e+10,1.391000e+10,2.146100e+10,3.903000e+10
1,VIPS,2014,3.734148e+09,1.1737,Consumer Defensive,9.285226e+08,1.345959e+08,7.939267e+08,2.805625e+09
2,KR,2014,9.837500e+10,0.0182,Consumer Defensive,2.023700e+10,2.725000e+09,1.751200e+10,7.813800e+10
3,RAD,2014,2.552641e+10,0.0053,Consumer Defensive,7.323734e+09,7.372520e+08,6.586482e+09,1.820268e+10
4,GIS,2014,1.790960e+10,0.0076,Consumer Defensive,6.369800e+09,2.957400e+09,3.412400e+09,1.153980e+10

In [77]:
financials.isnull().sum()

symbol                   0
year                     0
revenue               1171
revenue_growth        2088
sector                   0
gross_profit          1207
operating_income      1101
operating_expenses    1702
cost_of_revenue       1771
dtype: int64

In [78]:
financials.shape

(22077, 9)

In [79]:
financials = financials.dropna(subset=['revenue'])

In [80]:
financials=financials.fillna(0)

In [81]:
financials.isnull().sum()

symbol                0
year                  0
revenue               0
revenue_growth        0
sector                0
gross_profit          0
operating_income      0
operating_expenses    0
cost_of_revenue       0
dtype: int64

In [82]:
financials.reset_index(drop=True, inplace=True)

In [83]:
financials.to_csv("financial_data_2014-2018.csv",index=False)